---
title: "Individual_Assignment_5"
author: "Alex Gonzales"
format: 
 pdf:
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
execute: 
  message: false
  warning: false
---

# 1. Set up

## Packages
```{r}
#| label: packages

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# reading .xlxs files
library(readxl)

```


## Data

```{r}
#| label: data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

aq_ins <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"), 
  sheet = "Aquatic Insects")


# site information
sites <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"), 
  sheet = "sites")

# water quality
water_quality <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"), 
  sheet = "Water Quality",
  # powerful argument in read_xlsx to show the missing variables as numbers
  na = c("", "n/a", "N/A", "over", "173+"))

```



